language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

matrix:
  allow_failures:
    - python: 3.7-dev

before_install:
  - pip install flake8 codecov
before_script:
  - flake8 .
install:
  - pip install .
script: python setup.py nosetests
after_success:
  - codecov
