language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
before_install:
  - pip install codecov
install:
  - pip install .
script: nosetests --with-coverage
matrix:
  allow_failures:
    - python: 3.7-dev
after_success:
  - codecov
